### ISSUE TITLE
Error: spawn ENAMETOOLONG

### ISSUE THREAD

**Issue by matthdan003** [artiebits/fake-git-history#18]
Generating your GitHub activity was stuck for almost 30 minutes. When I stopped the process I got:
Error: spawn ENAMETOOLONG

![image](https://user-images.githubusercontent.com/46683029/96292192-fa62e780-0f9d-11eb-97d1-d10428bd1888.png)

**Comment by artiebits** [comment]
Hi @matthdan003, thank you for opening the issue. Indeed, it doesn't work for Windows and I will investigate it. I can suggest you to try this tool https://github.com/Shpota/github-activity-generator, I hope it will help you.

**Comment by matthdan003** [comment]
Hey man. Think you can please delete this issue? I would rather not have it show up in my contribution history

**Comment by matthdan003** [comment]
Thanks for your response though. The tool you recommended works perfectly

**Comment by artiebits** [comment]
sure thing, I will delete this issue. good luck!
