### ISSUE TITLE
Success 0 commits have been created

### ISSUE THREAD

**Issue by rahulxdd** [artiebits/fake-git-history#21]
After I run this command `npx fake-git-history --commitsPerDay "0,5" --startDate "2019/12/31" --endDate "2019/05/30"`

I get this message: `Success 0 commits have been created.                                  │
│         If you rely on this tool, please consider buying me a cup of coffee. I would appreciate it    │
│                                   https://www.buymeacoffee.com/artiebits`

Could you tell me what is the problem here?

**Comment by artiebits** [comment]
hi @rahulxdd, thank you for opening the issue! could you try to swap start and end dates please? `npx fake-git-history --commitsPerDay "0,5" --startDate "2019/05/30"  --endDate "2019/12/31"`. let me know if it helped

**Comment by rahulxdd** [comment]
It worked this time. I noticed one more thing. Created commits twice for same period and it generated commits for same dates each time. Can we randomise this?

**Comment by artiebits** [comment]
would be nice to see the video of how and what you are doing, thank you

**Comment by arinsanghia** [comment]
currently, it is not working

**Comment by artiebits** [comment]
@arinsanghia could you show me please what command you run?

**Comment by rahulxdd** [comment]
> would be nice to see the video of how and what you are doing, thank you

hi again... sorry I took more time to record this video and send it to you. Here it is: https://www.loom.com/share/7b53ae2015d24a64854f9b4c29f8c8e4 

Please take a look at let me know if you can fix it.

**Comment by artiebits** [comment]
hi @rahulxdd,

thank you very much for the video that clearly showing the bug. I will take a look and coma back to you

**Comment by rahulxdd** [comment]
> hi @rahulxdd,
> 
> thank you very much for the video that clearly showing the bug. I will take a look and come back to you

Thanks, can't wait.

**Comment by quentingosset** [comment]
I had the same problem with values like 5.10 I had a maximum of 3 daily commits. I think it's a problem with the await and the exec. I solved the problem on my side with my Fork. 
And i have send a PR : https://github.com/artiebits/fake-git-history/pull/22

**Comment by rahulxdd** [comment]
> I had the same problem with values like 5.10 I had a maximum of 3 daily commits. I think it's a problem with the await and the exec. I solved the problem on my side with my Fork.
> And i have send a PR : #22

Have you also checked the issues that I mentioned in the reply at the top and also in the video? And did you try checking the commit history when not logged in(for both private and public repo)?

**Comment by quentingosset** [comment]
for my part, the commits all had correctly different dates. I didn't need to test directly on github, I just used "git log" over a period of 1 day with a random between 5 and 10 commits and the result was that in my commit array I had 8 different dates correctly but in the git history I had only 3 commits. I calllbacked the exec() function errors and I found that on my 8 commits in my array in the loop at some point I had 6 error calllbacks. This is why I suspected a problem with the await sleep(150); which returns a single Promise. To avoid problems in my PR I made EVERY exec() command a Promise to make sure it executed.

**Comment by artiebits** [comment]
hi @rahulxdd 
I have published a beta version `1.4.0-beta.0` with a fix from @quentingosset. Looks like it solves your issue. Could you try it please?  `npx fake-git-history@1.4.0-beta.0 -s "2020/09/01" -e "2020/09/30" -c "3,5"`. Thank you

**Comment by rahulxdd** [comment]
@artiebits just checked 3 times. The number of commits are working fine but when I try to check the commit history from a private window it doesn't show anything. Can this fixed? @artiebits & @quentingosset

**Comment by quentingosset** [comment]
> @artiebits just checked 3 times. The number of commits are working fine but when I try to check the commit history from a private window it doesn't show anything. Can this fixed? @artiebits & @quentingosset

It's not a problem related on this script but it's a setttings on github ;)
![image](https://user-images.githubusercontent.com/6824137/99803433-b97c6680-2b39-11eb-89f4-6dc3d733c73c.png)
Enjoy.

**Comment by rahulxdd** [comment]
@artiebits you're right. I think you can merge the update code now. Thanks for all the help. :)

**Comment by artiebits** [comment]
I have released version 1.4.0, thank you both!
