### ISSUE TITLE
Program hangs on macOs Catalina

### ISSUE THREAD

**Issue by lijac** [artiebits/fake-git-history#26]
**Describe the bug**
`npx fake-git-history` hangs after making some commits.

**To Reproduce**
1. Open Zsh and locate to any directory which will have faked `my-history` folder.
2. Run `npx fake-git-history`.

**Expected behavior**
Should make all commits and complete successfully.

**Screenshots**
It hangs, and on `Ctrl+C` it displays the below error message.
![image](https://user-images.githubusercontent.com/39693487/127083440-9e4c6d20-82fe-4663-8c70-8164184cb2aa.png)

**Desktop (please complete the following information):**
 - OS: macOs Catalina 10.15.2
 - Terminal: iTerm2 3.3.12 with zsh

**Comment by artiebits** [comment]
hi @lijac , thanks for reporting the issue, i will take a look

**Comment by VincentRoma** [comment]
Hi,

I had the same issue on Ubuntu, I fixed it by setting: 
git config --global user.email "you@example.com"
git config --global user.name "Your Name"
Before running the command

Regards
