### ISSUE TITLE
Not working anymore for Windows

### ISSUE THREAD

**Issue by rahulxdd** [artiebits/fake-git-history#29]
It is stuck on the same date. Is it possible to fix it?

![image](https://user-images.githubusercontent.com/19429801/163811491-6ee78deb-894c-4b4f-b224-b557d39302b8.png)

**Comment by RayanAbid** [comment]
try restarting it. Worked for me

**Comment by amir504036** [comment]
> It is stuck on the same date. Is it possible to fix it?
> 
> ![image](https://user-images.githubusercontent.com/19429801/163811491-6ee78deb-894c-4b4f-b224-b557d39302b8.png)

Me too

**Comment by artiebits** [comment]
hi everyone, i've tested it several times on Mac and it works. Looks like the issue for Windows only. I will take a look. Thank you for reporting it

**Comment by simonloach** [comment]
Mine was stuck on both Ubuntu 20.04 and MacOS.

```
npx fake-git-history --commitsPerDay "1,5" --startDate "2020/04/01" --endDate "2022/07/01"
Need to install the following packages:
  fake-git-history@1.7.0
Ok to proceed? (y) y
⠹ Generating your Github activity... (April 23, 2020)
```

After 20 dates or so it got stuck on this certain one. Same thing on both systems, just different dates.

**Comment by artiebits** [comment]
Hi everyone. First of all, sorry for the delay in fixing this issue. Secondly, I have good news - I've fixed the issue and published a new version. Enjoy it!
