### ISSUE TITLE
Multiple github accounts

### ISSUE THREAD

**Issue by RayanAbid** [artiebits/fake-git-history#30]
Hi! 

I currently have 2 github accounts setup on my machine. But I want to use the second account which is not the default one. Is there any way of using the second account.

**Comment by artiebits** [comment]
Hi! Yes, just change your email and username in your .gitconfig https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-github-user-account/managing-email-preferences/setting-your-commit-email-address
