### ISSUE TITLE
Even update [Member since] item...

### ISSUE THREAD

**Issue by gsecret054** [artiebits/fake-git-history#33]
I've succeeded in making a trial of this `fake-git-history` function.
So the github calendar looks not so bad. It's okay.

BTW, I've noticed that **`Joined 21 days ago`** message on my user info!!!
It's located on `Member since` item.

How can I synchronize this date according to the fake-generated commits history?

**Comment by artiebits** [comment]
use `--startDate` option to generate commits from October 27, but the is no way to fake your "member since" date
