### ISSUE TITLE
Create a route of funding, besides going straight to your personal pocket

### ISSUE THREAD

**Issue by Sylk** [artiebits/fake-git-history#34]
I'm working on a PR for this repo to add 3 new flags and noticed that you have a link for personal donations after everything runs. While I have no personal gripes with this, it would be cool to see an [open collective link](https://opencollective.com/) for donations instead so that other stuff could be crowdfunded.

**Comment by artiebits** [comment]
i am closing this issue. the "funding that goes straight to my personal pocket" is $110 that I've made in 3 years from my 3 open source projects: pdf-to-printer, svelte-seo, and fake-git-history.
