### ISSUE TITLE
Possible Typo.

### ISSUE THREAD

**Issue by aroramrinaal** [artiebits/fake-git-history#37]
https://github.com/artiebits/fake-git-history/blob/af350c32ca6c0b0d9ed6174dd8992f9c283357ce/README.md?plain=1#L16

I think there is a possible typo since the line reads -  `push the changes: and push the changes: `

**Comment by artiebits** [comment]
hi @aroramrinaal , good catch. feel free to open a PR to fix it

**Comment by Venusdev2113** [comment]
great!

**Comment by Venusdev2113** [comment]
Thank you.
