### ISSUE TITLE
commits are showed in my-history, but not in my profile

### ISSUE THREAD

**Issue by SuperDev-star** [artiebits/fake-git-history#47]
Nice to meet you Artiebits.
I found your magic tool and tried to use.
Unfortunately, however, it didn't work for me.
I can see commits in my-history repo but can not see any contribution in profile after git remote and push operation.
Could you tell me what's wrong with me?
Sincerely.
![Untitled](https://github.com/artiebits/fake-git-history/assets/172194654/395dbc1a-9227-4734-94ca-9dbb5bcfee04)
![Untitled](https://github.com/artiebits/fake-git-history/assets/172194654/065eb62d-b515-4f50-912b-0fd145aaab19)

**Comment by artiebits** [comment]
hi there,

in the github settings, enable showing your contribution to private repos. hope this fixes your issue

![image](https://github.com/artiebits/fake-git-history/assets/29281882/3546f394-b9b7-4edf-b729-719b8a05d035)

**Comment by callmeberzerker** [comment]
I am pretty sure github changed something since doesn't work anymore.

**Comment by databasd** [comment]
> I am pretty sure github changed something since doesn't work anymore.

Seems to be the case, yes. Github seems to substitute date of any commit for the time that it was pushed to them.

Any idea if it's intentional or a bug?

**Comment by idea360** [comment]
https://github.com/orgs/community/discussions/22695#discussioncomment-3237743

**Comment by NoahDavidATL** [comment]
Can confirm. This no longer works.

**Comment by KagurazakaIris** [comment]
Confirm now, only valid for activities in the past year.

**Comment by KagurazakaIris** [comment]
But I rewrote a bash version, at least GitHub does not restrict this behavior.
