### ISSUE TITLE
Can't push the commits

### ISSUE THREAD

**Issue by Badrouu17** [artiebits/fake-git-history#5]
After I do all the steps correctly, I get this error :

![fakegit](https://user-images.githubusercontent.com/55046912/82138496-d184cd80-9818-11ea-9ee7-64dfb5460f41.png)

**Comment by artiebits** [comment]
Hi @Badrouu17. Sorry for the delay in response. Did you manage to solve the issue? I see your commit history is green ;)

**Comment by Badrouu17** [comment]
> Hi @Badrouu17. Sorry for the delay in response. Did you manage to solve the issue? I see your commit history is green ;)

Nope!

**Comment by artiebits** [comment]
I googled the error and it looks like it might happen if your local repo is not in sync with the git repo. could you check solutions from this post please https://stackoverflow.com/questions/24114676/git-error-failed-to-push-some-refs-to-remote

**Comment by victorykop** [comment]
Hi @Badrouu17 
I want to exclude Saturdays and Sundays when making commits from March 1st to September 1st.

Is this possible?
